name       : hub
version    : 2.6.0
release    : 4
source     :
    - https://github.com/github/hub/archive/v2.6.0.tar.gz : c4df5ce953aa5dd5c4fa57ada96559b4b76bbd30a9e961e10e881be869cf4f2c
license    : MIT
component  : system.utils
summary    : A command line tool that wraps git in order to extend it with extra features and commands that make working with GitHub easier
description: |
    hub is a command line tool that wraps git in order to extend it with extra features and commands that make working with GitHub easier.
builddeps  :
    - golang
build      : |
    mkdir -p src/github.com/github
    export GOPATH=`pwd`
    ln -sv `pwd` src/github.com/github/hub
    cd src/github.com/github/hub
    ./script/build
install    : |
    install -Dm00775 bin/hub $installdir/usr/bin/hub
