name       : hub
version    : 2.2.9
release    : 1
source     :
    - https://github.com/github/hub/archive/v2.2.9.tar.gz : b3cf227e38a34a56e37b7705a60bec258cea52174d8e030b559f74af647a70d6
license    : MIT
component  : system.utils
summary    : A command line tool that wraps git in order to extend it with extra features and commands that make working with GitHub easier
description: |
    hub is a command line tool that wraps git in order to extend it with extra features and commands that make working with GitHub easier.
builddeps  :
    - golang
build      : |
    ./script/build
install    : |
    install -Dm00775 bin/hub $installdir/usr/bin/hub
