name       : hub
version    : 2.7.0
release    : 6
source     :
    - https://github.com/github/hub/archive/v2.7.0.tar.gz : 58d131c32404c963b06bcc067bda14317bc22be26187026a91960aecda324bf4
license    : MIT
component  : system.utils
summary    : A command line tool that wraps git in order to extend it with extra features and commands that make working with GitHub easier
description: |
    hub is a command line tool that wraps git in order to extend it with extra features and commands that make working with GitHub easier.
builddeps  :
    - golang
build      : |
    mkdir -p src/github.com/github
    export GOPATH=`pwd`
    ln -sv `pwd` src/github.com/github/hub
    cd src/github.com/github/hub
    ./script/build
install    : |
    install -Dm00775 bin/hub $installdir/usr/bin/hub
