name       : hub
version    : 2.9.0
release    : 9
source     :
    - git|https://github.com/github/hub.git : v2.9.0
license    : MIT
component  : system.utils
summary    : A command line tool that wraps git in order to extend it with extra features and commands that make working with GitHub easier
description: |
    hub is a command line tool that wraps git in order to extend it with extra features and commands that make working with GitHub easier.
builddeps  :
    - golang
    - groff
build      : |
    mkdir -p src/github.com/github
    export GOPATH=`pwd`
    ln -sv `pwd` src/github.com/github/hub
    cd src/github.com/github/hub
    export prefix=$installdir/usr
    %make install
