name       : hub
version    : 2.4.0
release    : 3
source     :
    - https://github.com/github/hub/archive/v2.4.0.tar.gz : 894eb112be9aa0464fa2c63f48ae8e573ef9e32a00bad700e27fd09a0cb3be4b
license    : MIT
component  : system.utils
summary    : A command line tool that wraps git in order to extend it with extra features and commands that make working with GitHub easier
description: |
    hub is a command line tool that wraps git in order to extend it with extra features and commands that make working with GitHub easier.
builddeps  :
    - golang
build      : |
    ./script/build
install    : |
    install -Dm00775 bin/hub $installdir/usr/bin/hub
