name       : hub
version    : 2.3.0
release    : 2
source     :
    - https://github.com/github/hub/archive/v2.3.0.tar.gz : 69e48105f7287537e7afaf969825666c1f09267eae3507515151900487342fae
license    : MIT
component  : system.utils
summary    : A command line tool that wraps git in order to extend it with extra features and commands that make working with GitHub easier
description: |
    hub is a command line tool that wraps git in order to extend it with extra features and commands that make working with GitHub easier.
builddeps  :
    - golang
build      : |
    ./script/build
install    : |
    install -Dm00775 bin/hub $installdir/usr/bin/hub
